<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Adding Telerik HTML5 Report Viewer page log</title>
    <style>
        body {
            background: #fff;
            color: #505050;
            font: 14px 'Segoe UI', tahoma, arial, helvetica, sans-serif;
            margin: 20px;
            padding: 0;
        }

        #header {
            background: #efefef;
            padding: 0;
        }

        /* Start: Toggle details */
        label { 
            top:0; 
            left:0; 
            font-weight:700; 
            margin-top: 10px;
            user-select: none;
            -ms-user-select: none;
        }

            label:hover{
                color: cadetblue;
                border-color: #505050;
            }

        input#show, input#hide {
            display:none;
        }

        ul#details {
            transition: opacity 1s ease-out;
            opacity: 0; 
            height: 0;
            font-size: 0;
            overflow: hidden;
        }

        input#show:checked ~ .show:before {
            content: "";
        }

        input#show:checked ~ .hide:before {
            content: "Hide details";
            border: solid;
            padding: 3px;
        }

        input#hide:checked ~ .hide:before {
            content: "";
        }

        input#hide:checked ~ .show:before {
            content: "Show details"; 
            border: solid;
            padding: 3px;
        }

        input#show:checked ~ ul#details {
            opacity: 1;
            font-size: 100%;
            height: auto;
            padding: 10px;
        }

        input#hide:checked ~ ul#details {
            transition: opacity 1s ease-out;
            opacity: 0; 
            height: 0;
            font-size: 0;
            overflow: hidden;
        }

        /* End: toggle details */


        h1 {
            font-size: 48px;
            font-weight: normal;
            margin: 0;
            padding: 0 30px;
            line-height: 150px;
        }

        p {
            font-size: 18px;
            color: #fff;
            background: #969696;
            padding: 0 30px;
            line-height: 50px;
        }

        #main {
            padding: 5px 30px;
        }

        .section {
            width: 21.7%;
            float: left;
            margin: 0 0 0 40px;
        }

            .section h2 {
                font-size: 13px;
                text-transform: uppercase;
                margin: 0;
                border-bottom: 1px solid silver;
                padding-bottom: 12px;
                margin-bottom: 8px;
            }

            .section.first {
                margin-left: 0;
                width: 25%
            }

                .section.first h2 {
                    font-size: 20px;
                    text-transform: none;
                    margin-bottom: 16px;
                    border: none;
                }

                .section.first li {
                    border-top: 1px solid silver;
                    padding: 8px 0;
                }

            .section.last {
                margin-right: 0;
                width: 70%;
            }
            
            .section.last h2 {
                    font-size: 20px;
                    text-transform: none;
                    margin-bottom: 5px;
                    border: none;
                }

            .section.last li {
                padding: 4px 0;
                border-bottom: solid;
                border-bottom-width: 1px;
                border-color: lightgray;
            }
            
            .section.last ul{
                padding-bottom:10px;   
                margin-bottom: 10px; 
            }
            
                

        ul {
            list-style: none;
            padding: 0;
            margin: 0;
            line-height: 20px;
        }



        a {
            color: #267cb2;
            text-decoration: none;
        }

            a:hover {
                text-decoration: underline;
            }


    </style>
</head>
<body>

    <div id="header">
        <p><span style="color: red;">ERROR!</span> An error occurred while adding an HTML page with Telerik HTML5 Report Viewer</p>
    </div>

    <div id="main">
        <div class="section first">
            <h2>Telerik HTML5 Report Viewer enabled application consists of: </h2>
            <ul>
                <li><a href="http://www.telerik.com/help/reporting/html5-report-viewer.html" >HTML5 Report Viewer</a> prerequisites</li>
                <li>HTML page with HTML5 Report Viewer</li>
                <li><a href="http://www.telerik.com/help/reporting/telerik-reporting-rest-conception.html" >Telerik Reporting REST Service</a> with its prerequisites</li>
            </ul>
        </div>

        <div class="section last">
            <h2>Summary</h2>
            <ul style="padding-bottom: 10px; padding-left: 7px;">
                <li style="color: none;">Added folder: Reports</li>
<li style="color: none;">Added SampleReport.trdx</li>
<li style="color: #FF6600;">Warning: Can not add reference to: Telerik.Reporting.Services.WebApi</li>
<li style="color: #FF6600;">Warning: Can not add reference to: Telerik.Reporting.XpsRendering</li>
<li style="color: none;">Installed NuGet package: Newtonsoft.Json 4.5.11</li>
<li style="color: #FF0000;">Error: System.InvalidOperationException: An error occurred while retrieving package metadata for 'Newtonsoft.Json.4.5.11' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: An error occurred while retrieving package metadata for 'Newtonsoft.Json.4.5.11' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: The V2 feed at 'https://packages.nuget.org/FindPackagesById()?id='Newtonsoft.Json'' returned an unexpected status code '404 Not Found'.
   en NuGet.Protocol.V2FeedParser.&lt;QueryV2Feed&gt;d__50.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;FindPackagesByIdAsync&gt;d__42.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;GetPackage&gt;d__41.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageFromSourceAsync&gt;d__27.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageAsync&gt;d__26.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;&gt;c__DisplayClass25_0.&lt;&lt;StartWorkerTasks&gt;b__0&gt;d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;ProcessResultsAsync&gt;d__24.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;StartTasksAndProcessWork&gt;d__21.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__20.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__19.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;InstallPackageAsync&gt;d__32.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   en NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   en Telerik.ReportViewer.Html5.Design.NugetManager.InstallPackage(String package, String version)</li>
<li style="color: none;">Installed NuGet package: Microsoft.Net.Http 2.0.20710.0</li>
<li style="color: #FF0000;">Error: System.InvalidOperationException: An error occurred while retrieving package metadata for 'Microsoft.Net.Http.2.0.20710' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: An error occurred while retrieving package metadata for 'Microsoft.Net.Http.2.0.20710' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: The V2 feed at 'https://packages.nuget.org/FindPackagesById()?id='Microsoft.Net.Http'' returned an unexpected status code '404 Not Found'.
   en NuGet.Protocol.V2FeedParser.&lt;QueryV2Feed&gt;d__50.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;FindPackagesByIdAsync&gt;d__42.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;GetPackage&gt;d__41.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageFromSourceAsync&gt;d__27.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageAsync&gt;d__26.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;&gt;c__DisplayClass25_0.&lt;&lt;StartWorkerTasks&gt;b__0&gt;d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;ProcessResultsAsync&gt;d__24.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;StartTasksAndProcessWork&gt;d__21.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__20.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__19.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;InstallPackageAsync&gt;d__32.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   en NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   en Telerik.ReportViewer.Html5.Design.NugetManager.InstallPackage(String package, String version)</li>
<li style="color: none;">Installed NuGet package: Microsoft.AspNet.WebApi.Client 4.0.30506</li>
<li style="color: #FF0000;">Error: System.InvalidOperationException: An error occurred while retrieving package metadata for 'Microsoft.AspNet.WebApi.Client.4.0.30506' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: An error occurred while retrieving package metadata for 'Microsoft.AspNet.WebApi.Client.4.0.30506' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: The V2 feed at 'https://packages.nuget.org/FindPackagesById()?id='Microsoft.AspNet.WebApi.Client'' returned an unexpected status code '404 Not Found'.
   en NuGet.Protocol.V2FeedParser.&lt;QueryV2Feed&gt;d__50.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;FindPackagesByIdAsync&gt;d__42.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;GetPackage&gt;d__41.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageFromSourceAsync&gt;d__27.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageAsync&gt;d__26.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;&gt;c__DisplayClass25_0.&lt;&lt;StartWorkerTasks&gt;b__0&gt;d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;ProcessResultsAsync&gt;d__24.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;StartTasksAndProcessWork&gt;d__21.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__20.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__19.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;InstallPackageAsync&gt;d__32.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   en NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   en Telerik.ReportViewer.Html5.Design.NugetManager.InstallPackage(String package, String version)</li>
<li style="color: none;">Installed NuGet package: Microsoft.AspNet.WebApi.Core 4.0.30506</li>
<li style="color: #FF0000;">Error: System.InvalidOperationException: An error occurred while retrieving package metadata for 'Microsoft.AspNet.WebApi.Core.4.0.30506' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: An error occurred while retrieving package metadata for 'Microsoft.AspNet.WebApi.Core.4.0.30506' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: The V2 feed at 'https://packages.nuget.org/FindPackagesById()?id='Microsoft.AspNet.WebApi.Core'' returned an unexpected status code '404 Not Found'.
   en NuGet.Protocol.V2FeedParser.&lt;QueryV2Feed&gt;d__50.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;FindPackagesByIdAsync&gt;d__42.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;GetPackage&gt;d__41.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageFromSourceAsync&gt;d__27.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageAsync&gt;d__26.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;&gt;c__DisplayClass25_0.&lt;&lt;StartWorkerTasks&gt;b__0&gt;d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;ProcessResultsAsync&gt;d__24.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;StartTasksAndProcessWork&gt;d__21.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__20.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__19.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;InstallPackageAsync&gt;d__32.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   en NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   en Telerik.ReportViewer.Html5.Design.NugetManager.InstallPackage(String package, String version)</li>
<li style="color: none;">Installed NuGet package: Microsoft.Web.Infrastructure 1.0.0.0</li>
<li style="color: #FF0000;">Error: System.InvalidOperationException: An error occurred while retrieving package metadata for 'Microsoft.Web.Infrastructure.1.0.0' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: An error occurred while retrieving package metadata for 'Microsoft.Web.Infrastructure.1.0.0' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: The V2 feed at 'https://packages.nuget.org/FindPackagesById()?id='Microsoft.Web.Infrastructure'' returned an unexpected status code '404 Not Found'.
   en NuGet.Protocol.V2FeedParser.&lt;QueryV2Feed&gt;d__50.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;FindPackagesByIdAsync&gt;d__42.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;GetPackage&gt;d__41.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageFromSourceAsync&gt;d__27.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageAsync&gt;d__26.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;&gt;c__DisplayClass25_0.&lt;&lt;StartWorkerTasks&gt;b__0&gt;d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;ProcessResultsAsync&gt;d__24.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;StartTasksAndProcessWork&gt;d__21.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__20.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__19.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;InstallPackageAsync&gt;d__32.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   en NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   en Telerik.ReportViewer.Html5.Design.NugetManager.InstallPackage(String package, String version)</li>
<li style="color: none;">Installed NuGet package: Microsoft.AspNet.WebApi.WebHost 4.0.30506</li>
<li style="color: #FF0000;">Error: System.InvalidOperationException: An error occurred while retrieving package metadata for 'Microsoft.AspNet.WebApi.WebHost.4.0.30506' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: An error occurred while retrieving package metadata for 'Microsoft.AspNet.WebApi.WebHost.4.0.30506' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: The V2 feed at 'https://packages.nuget.org/FindPackagesById()?id='Microsoft.AspNet.WebApi.WebHost'' returned an unexpected status code '404 Not Found'.
   en NuGet.Protocol.V2FeedParser.&lt;QueryV2Feed&gt;d__50.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;FindPackagesByIdAsync&gt;d__42.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;GetPackage&gt;d__41.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageFromSourceAsync&gt;d__27.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageAsync&gt;d__26.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;&gt;c__DisplayClass25_0.&lt;&lt;StartWorkerTasks&gt;b__0&gt;d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;ProcessResultsAsync&gt;d__24.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;StartTasksAndProcessWork&gt;d__21.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__20.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__19.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;InstallPackageAsync&gt;d__32.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   en NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   en Telerik.ReportViewer.Html5.Design.NugetManager.InstallPackage(String package, String version)</li>
<li style="color: none;">Added Global.asax</li>
<li style="color: #FF0000;">Error: GetFirstNamespace. Elements is null.</li>
<li style="color: #FF0000;">Error: GetFirstClass. Elements is null.</li>
<li style="color: #FF0000;">Error: Fail to register Global.asax routes. 
 System.Exception: Can not resolve application start function.
   en Telerik.ReportViewer.Html5.Design.GlobalAsaxManager.EnhanceCodefile()</li>
<li style="color: none;">Added Html5ReportViewer1.html</li>
<li style="color: none;">Added folder: Controllers</li>
<li style="color: none;">Added ReportsController.cs</li>
<li style="color: none;">Added folder: ReportViewer</li>
<li style="color: none;">Added folder: js</li>
<li style="color: none;">Added telerikReportViewer-10.0.16.204.min.js</li>
<li style="color: none;">Added kendo.subset.2015.3.930.min.js</li>

            </ul>

            <input type="radio" id="show" name="group" />   
            <input type="radio" id="hide" name="group" checked />
            <label for="hide" class="hide" unselectable="on"></label>
            <label for="show" class="show" unselectable="on"></label> 

            <ul id="details">
                20/06/2020 15:06:05
<li style="color: none;">Build Started</li>
<li style="color: none;">Check Framework Support</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : BarcodeLib</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : Bunifu_UI_v1.5.3</li>
<li style="color: none;">Assembly Version: 1.5.3.0</li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : CrystalDecisions.CrystalReports.Engine</li>
<li style="color: none;">Assembly Version: 13.0.3500.0</li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : CrystalDecisions.Data.AdoDotNetInterop</li>
<li style="color: none;">Assembly Version: 13.0.2000.0</li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : CrystalDecisions.ReportSource</li>
<li style="color: none;">Assembly Version: 13.0.3500.0</li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : CrystalDecisions.Shared</li>
<li style="color: none;">Assembly Version: 13.0.3500.0</li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : CrystalDecisions.Windows.Forms</li>
<li style="color: none;">Assembly Version: 13.0.3500.0</li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : FlashControlV71</li>
<li style="color: none;">Assembly Version: 1.0.3187.32366</li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : Guna.UI</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : Microsoft.ReportViewer.Common</li>
<li style="color: none;">Assembly Version: 11.0.0.0</li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : Microsoft.ReportViewer.WinForms</li>
<li style="color: none;">Assembly Version: 11.0.0.0</li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : Microsoft.VisualBasic</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : PlaceholderTextBox</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : System</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : System.Configuration</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : System.Core</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : System.Design</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : System.DirectoryServices</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : System.Drawing</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : System.Management</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : System.Web</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : System.Web.Services</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : System.Windows.Forms</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : System.Windows.Forms.DataVisualization</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : System.Xml.Linq</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : System.Data.DataSetExtensions</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : Microsoft.CSharp</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : System.Data</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : System.Xml</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : Telerik.Reporting</li>
<li style="color: none;">Assembly Version: 10.0.16.204</li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : Telerik.ReportViewer.WinForms</li>
<li style="color: none;">Assembly Version: 10.0.16.204</li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : XanderUI</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Assembly name is null: False</li>
<li style="color: none;">Assembly : zxing</li>
<li style="color: none;">Assembly Version: </li>
<li style="color: none;">Product Version: 10.0.16.204</li>
<li style="color: none;">Verify Telerik Reporting Version: True</li>
<li style="color: none;">Added folder: Reports</li>
<li style="color: none;">Added SampleReport.trdx</li>
<li style="color: none;">Cancel the form closing: False</li>
<li style="color: none;">Add required references.</li>
<li style="color: none;">Add project references</li>
<li style="color: none;">Get project references.</li>
<li style="color: none;">Reference already available: Telerik.Reporting, Version=10.0.16.204, Culture=neutral, PublicKeyToken=a9d7983dfcc261be</li>
<li style="color: #FF6600;">Warning: Can not add reference to: Telerik.Reporting.Services.WebApi</li>
<li style="color: none;">System.Runtime.InteropServices.COMException (0x80004005): Error del proveedor extensor al devolver un extensor para este objeto.
   en VSLangProj.References.Add(String bstrPath)
   en Telerik.Reporting.Vs.Common.ProjectManager.EnsureReference(Boolean copyLocal, String[] referencesToAdd)</li>
<li style="color: #FF6600;">Warning: Can not add reference to: Telerik.Reporting.XpsRendering</li>
<li style="color: none;">System.Runtime.InteropServices.COMException (0x80004005): Devuelto error HRESULT E_FAIL de una llamada a un componente COM.
   en VSLangProj.References.Add(String bstrPath)
   en Telerik.Reporting.Vs.Common.ProjectManager.EnsureReference(Boolean copyLocal, String[] referencesToAdd)</li>
<li style="color: none;">Verify Newtonsoft.Json package version</li>
<li style="color: none;">Installed NuGet package: Newtonsoft.Json 4.5.11</li>
<li style="color: #FF0000;">Error: System.InvalidOperationException: An error occurred while retrieving package metadata for 'Newtonsoft.Json.4.5.11' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: An error occurred while retrieving package metadata for 'Newtonsoft.Json.4.5.11' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: The V2 feed at 'https://packages.nuget.org/FindPackagesById()?id='Newtonsoft.Json'' returned an unexpected status code '404 Not Found'.
   en NuGet.Protocol.V2FeedParser.&lt;QueryV2Feed&gt;d__50.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;FindPackagesByIdAsync&gt;d__42.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;GetPackage&gt;d__41.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageFromSourceAsync&gt;d__27.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageAsync&gt;d__26.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;&gt;c__DisplayClass25_0.&lt;&lt;StartWorkerTasks&gt;b__0&gt;d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;ProcessResultsAsync&gt;d__24.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;StartTasksAndProcessWork&gt;d__21.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__20.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__19.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;InstallPackageAsync&gt;d__32.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   en NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   en Telerik.ReportViewer.Html5.Design.NugetManager.InstallPackage(String package, String version)</li>
<li style="color: none;">Verify Microsoft.Net.Http package version</li>
<li style="color: none;">Installed NuGet package: Microsoft.Net.Http 2.0.20710.0</li>
<li style="color: #FF0000;">Error: System.InvalidOperationException: An error occurred while retrieving package metadata for 'Microsoft.Net.Http.2.0.20710' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: An error occurred while retrieving package metadata for 'Microsoft.Net.Http.2.0.20710' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: The V2 feed at 'https://packages.nuget.org/FindPackagesById()?id='Microsoft.Net.Http'' returned an unexpected status code '404 Not Found'.
   en NuGet.Protocol.V2FeedParser.&lt;QueryV2Feed&gt;d__50.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;FindPackagesByIdAsync&gt;d__42.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;GetPackage&gt;d__41.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageFromSourceAsync&gt;d__27.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageAsync&gt;d__26.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;&gt;c__DisplayClass25_0.&lt;&lt;StartWorkerTasks&gt;b__0&gt;d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;ProcessResultsAsync&gt;d__24.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;StartTasksAndProcessWork&gt;d__21.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__20.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__19.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;InstallPackageAsync&gt;d__32.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   en NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   en Telerik.ReportViewer.Html5.Design.NugetManager.InstallPackage(String package, String version)</li>
<li style="color: none;">Verify Microsoft.AspNet.WebApi.Client package version</li>
<li style="color: none;">Installed NuGet package: Microsoft.AspNet.WebApi.Client 4.0.30506</li>
<li style="color: #FF0000;">Error: System.InvalidOperationException: An error occurred while retrieving package metadata for 'Microsoft.AspNet.WebApi.Client.4.0.30506' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: An error occurred while retrieving package metadata for 'Microsoft.AspNet.WebApi.Client.4.0.30506' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: The V2 feed at 'https://packages.nuget.org/FindPackagesById()?id='Microsoft.AspNet.WebApi.Client'' returned an unexpected status code '404 Not Found'.
   en NuGet.Protocol.V2FeedParser.&lt;QueryV2Feed&gt;d__50.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;FindPackagesByIdAsync&gt;d__42.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;GetPackage&gt;d__41.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageFromSourceAsync&gt;d__27.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageAsync&gt;d__26.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;&gt;c__DisplayClass25_0.&lt;&lt;StartWorkerTasks&gt;b__0&gt;d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;ProcessResultsAsync&gt;d__24.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;StartTasksAndProcessWork&gt;d__21.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__20.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__19.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;InstallPackageAsync&gt;d__32.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   en NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   en Telerik.ReportViewer.Html5.Design.NugetManager.InstallPackage(String package, String version)</li>
<li style="color: none;">Verify Microsoft.AspNet.WebApi.Core package version</li>
<li style="color: none;">Installed NuGet package: Microsoft.AspNet.WebApi.Core 4.0.30506</li>
<li style="color: #FF0000;">Error: System.InvalidOperationException: An error occurred while retrieving package metadata for 'Microsoft.AspNet.WebApi.Core.4.0.30506' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: An error occurred while retrieving package metadata for 'Microsoft.AspNet.WebApi.Core.4.0.30506' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: The V2 feed at 'https://packages.nuget.org/FindPackagesById()?id='Microsoft.AspNet.WebApi.Core'' returned an unexpected status code '404 Not Found'.
   en NuGet.Protocol.V2FeedParser.&lt;QueryV2Feed&gt;d__50.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;FindPackagesByIdAsync&gt;d__42.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;GetPackage&gt;d__41.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageFromSourceAsync&gt;d__27.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageAsync&gt;d__26.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;&gt;c__DisplayClass25_0.&lt;&lt;StartWorkerTasks&gt;b__0&gt;d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;ProcessResultsAsync&gt;d__24.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;StartTasksAndProcessWork&gt;d__21.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__20.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__19.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;InstallPackageAsync&gt;d__32.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   en NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   en Telerik.ReportViewer.Html5.Design.NugetManager.InstallPackage(String package, String version)</li>
<li style="color: none;">Verify Microsoft.Web.Infrastructure package version</li>
<li style="color: none;">Installed NuGet package: Microsoft.Web.Infrastructure 1.0.0.0</li>
<li style="color: #FF0000;">Error: System.InvalidOperationException: An error occurred while retrieving package metadata for 'Microsoft.Web.Infrastructure.1.0.0' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: An error occurred while retrieving package metadata for 'Microsoft.Web.Infrastructure.1.0.0' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: The V2 feed at 'https://packages.nuget.org/FindPackagesById()?id='Microsoft.Web.Infrastructure'' returned an unexpected status code '404 Not Found'.
   en NuGet.Protocol.V2FeedParser.&lt;QueryV2Feed&gt;d__50.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;FindPackagesByIdAsync&gt;d__42.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;GetPackage&gt;d__41.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageFromSourceAsync&gt;d__27.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageAsync&gt;d__26.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;&gt;c__DisplayClass25_0.&lt;&lt;StartWorkerTasks&gt;b__0&gt;d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;ProcessResultsAsync&gt;d__24.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;StartTasksAndProcessWork&gt;d__21.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__20.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__19.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;InstallPackageAsync&gt;d__32.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   en NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   en Telerik.ReportViewer.Html5.Design.NugetManager.InstallPackage(String package, String version)</li>
<li style="color: none;">Verify Microsoft.AspNet.WebApi.WebHost package version</li>
<li style="color: none;">Installed NuGet package: Microsoft.AspNet.WebApi.WebHost 4.0.30506</li>
<li style="color: #FF0000;">Error: System.InvalidOperationException: An error occurred while retrieving package metadata for 'Microsoft.AspNet.WebApi.WebHost.4.0.30506' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: An error occurred while retrieving package metadata for 'Microsoft.AspNet.WebApi.WebHost.4.0.30506' from source 'http://packages.nuget.org'. ---&gt; NuGet.Protocol.Core.Types.FatalProtocolException: The V2 feed at 'https://packages.nuget.org/FindPackagesById()?id='Microsoft.AspNet.WebApi.WebHost'' returned an unexpected status code '404 Not Found'.
   en NuGet.Protocol.V2FeedParser.&lt;QueryV2Feed&gt;d__50.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;FindPackagesByIdAsync&gt;d__42.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.V2FeedParser.&lt;GetPackage&gt;d__41.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.Protocol.DependencyInfoResourceV2Feed.&lt;ResolvePackage&gt;d__4.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageFromSourceAsync&gt;d__27.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherPackageAsync&gt;d__26.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;&gt;c__DisplayClass25_0.&lt;&lt;StartWorkerTasks&gt;b__0&gt;d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;ProcessResultsAsync&gt;d__24.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;StartTasksAndProcessWork&gt;d__21.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__20.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.ResolverGather.&lt;GatherAsync&gt;d__19.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en NuGet.PackageManagement.NuGetPackageManager.&lt;PreviewInstallPackageAsync&gt;d__48.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NuGet.PackageManagement.NuGetPackageManager.&lt;InstallPackageAsync&gt;d__32.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en NuGet.VisualStudio.VsPackageInstaller.&lt;InstallInternalAsync&gt;d__25.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   en NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   en Telerik.ReportViewer.Html5.Design.NugetManager.InstallPackage(String package, String version)</li>
<li style="color: none;">Added Global.asax</li>
<li style="color: none;">Enhance Global.asax</li>
<li style="color: #FF0000;">Error: GetFirstNamespace. Elements is null.</li>
<li style="color: #FF0000;">Error: GetFirstClass. Elements is null.</li>
<li style="color: #FF0000;">Error: Fail to register Global.asax routes. 
 System.Exception: Can not resolve application start function.
   en Telerik.ReportViewer.Html5.Design.GlobalAsaxManager.EnhanceCodefile()</li>
<li style="color: none;">Class with name ReportsController is not found</li>
<li style="color: none;">Adding TelerikViewerPage.html.ServiceUrl project item</li>
<li style="color: none;">Added Html5ReportViewer1.html</li>
<li style="color: none;">Adding TelerikViewerPage.html.ReportServer project item</li>
<li style="color: none;">Added folder: Controllers</li>
<li style="color: none;">Added ReportsController.cs</li>
<li style="color: none;">Added folder: ReportViewer</li>
<li style="color: none;">Added folder: js</li>
<li style="color: none;">Added telerikReportViewer-10.0.16.204.min.js</li>
<li style="color: none;">Folder ReportViewer already exists</li>
<li style="color: none;">Folder js already exists</li>
<li style="color: none;">Added kendo.subset.2015.3.930.min.js</li>

            </ul>
        </div>
    </div>

</body>
</html>